INSERT INTO category (description) VALUES ('American');
INSERT INTO category (description) VALUES ('German');
INSERT INTO category (description) VALUES ('Italian');
INSERT INTO category (description) VALUES ('Spanish');
INSERT INTO category (description) VALUES ('Ukranian');
INSERT INTO unit_of_measure (description) VALUES ('Teaspoon');
INSERT INTO unit_of_measure (description) VALUES ('Tablespoon');
INSERT INTO unit_of_measure (description) VALUES ('Cup');
INSERT INTO unit_of_measure (description) VALUES ('Pinch');